[package]
name = "consensus"
version = "0.0.1"
edition = "2021"
description = "T-chain's proof of work consensus algorithm implementation"
license = "MIT OR Apache-2.0"
readme="../README.md"

[dependencies]